spring.application.name=currency-converter

# Server
server.port=8081

# Exchange Rate API Configuration
exchange.api.base-url=https://open.er-api.com/v6

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/api-docs
